name: Compare Functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello, World!', 'World') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello, World!', 'd!') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello, World!', 'He') }}